language: java
jdk: oraclejdk7
before_install:
- openssl aes-256-cbc -K $encrypted_48e9b680972d_key -iv $encrypted_48e9b680972d_iv
  -in tools/deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- echo skipped
before_script:
- mv -fv tools/deploy/ssh_config ~/.ssh/config
after_script:
- git remote add deploy root@spreadsheet:/usr/local/codelib/table.git
- git push deploy $TRAVIS_BRANCH --force
after_success:
- mvn clean test jacoco:report coveralls:report
cache:
  directories:
  - "$HOME/.m2"
group: stable
dist: precise
os: linux
